---
title: 'Impact of active learning on STEM achievement: Systematic review and new causal
  evidence'
author: "Prashant Loyalka, Mridul Joshi, Saurabh Khanna, and Paul Glewwe"
date: "27 August 2024"
output:
  pdf_document:
    extra_dependencies:
    - dcolumn
    - booktabs
    - caption
    - float
    toc: no
    toc_depth: 6
    keep_tex: yes
    number_sections: yes
  html_document:
    toc: no
    toc_depth: '6'
    df_print: paged
urlcolor: blue
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.retina = 4)
```

```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(estimatr, texreg, janitor, tidyverse, skimr, compareGroups)
```

# Experimental Sample

## Table 3: Main effects

```{r}
df <- 
  read_csv("/data/data_exp_sample.csv")
```

```{r, results='asis'}
lm1 <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(course_rank ~ fac_active_teaching, data = ., fixed_effects = ~ fe_var, se_type = "stata", clusters = facultyid)

lm2 <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(course_rank ~ fac_active_teaching + female + ses + reservation_stu + rural + father_college + mother_college, data = ., fixed_effects = ~ fe_var, se_type = "stata", clusters = facultyid)

lm3 <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(course_rank ~ fac_active_teaching, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm4 <-
  df %>% 
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(course_rank ~ fac_active_teaching + female + ses + reservation_stu + rural + father_college + mother_college + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ fe_var, se_type = "stata", clusters = facultyid)

lm5 <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

knitreg(list(lm1, lm2, lm3, lm4, lm5), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = T, dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 3, include.rsquared = F, include.adjrs = F, include.rmse = F, include.nclust = F)
```

\newpage

## Table 4: Heterogeneous effects

```{r, results='asis'}
lm1a <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(female == 0) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm1b <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(female == 1) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm2a <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(ses_lowest_tercile == 0) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm2b <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(ses_lowest_tercile == 1) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm3a <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(math_lowest_tercile == 0) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm3b <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(math_lowest_tercile == 1) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm4a <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(rural == 0) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm4b <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(rural == 1) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm5a <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(reservation_stu == 0) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

lm5b <-
  df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  filter(reservation_stu == 1) %>%
  lm_robust(course_rank ~ fac_active_teaching + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ studentid + fe_var, se_type = "stata", clusters = facultyid)

knitreg(list(lm1a, lm1b, lm2a, lm2b, lm3a, lm3b, lm4a, lm4b, lm5a, lm5b), stars = c(0.01, 0.05, 0.1), include.ci = TRUE, dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 3, include.rsquared = F, include.adjrs = F, include.rmse = F, include.nclust = F, custom.coef.map = list("fac_active_teaching" = "Active learning"), custom.model.names = c("Male", "Female", "High/medium SES", "Low SES", "High math skills", "Low math skills", "Urban", "Rural", "Non-reservation", "Reservation"))
```

\newpage

## Table E3

Student characteristics:

```{r}
df %>%
  distinct(studentid, .keep_all = T) %>%
  skim(female, rural, reservation_stu, father_college, mother_college)
```

```{r}
df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(fac_active_teaching ~  female + rural + reservation_stu + father_college + mother_college, data = ., fixed_effects = ~ fe_var, se_type = "stata", clusters = facultyid) %>%
  summary()
```

Faculty characteristics:

```{r}
df %>%
  distinct(facultyid, .keep_all = T) %>%
  skim(fac_associate_professor, fac_professor, fac_yearsinhighed, fac_highest_degree_phd, fac_highest_degree_phd_in_prog, fac_degree_college_elite, fac_female)
```

```{r}
df %>%
  mutate(fe_var = str_c(departmentid, coursename, sep = "_")) %>%
  lm_robust(fac_active_teaching ~ fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ fe_var, se_type = "stata", clusters = facultyid) %>%
  summary()
```

\newpage

# Cross-country sample

## Table 5: Main effects

```{r}
df <- 
  read_csv("/data/data_qexp_sample.csv")
```

```{r, results='asis'}
lm1 <-
  df %>% 
  filter(country == "China") %>%
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm2 <-
  df %>%
  filter(country == "India") %>%
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm3 <-
  df %>%
  filter(country == "Russia") %>%
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

knitreg(list(lm1, lm2, lm3), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = TRUE, custom.model.names = c("China", "India", "Russia"), dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 3, include.rsquared = F, include.adjrs = F, include.rmse = F, include.nclust = F, custom.coef.names = c("Active learning", "Baseline achievement", "Faculty experience", "Faculty undergrad from elite college", "Faculty graduate from elite college", "Faculty total publications", "Faculty female", "Faculty highest degree is PhD", "Professor", "Associate Professor"), label = "tab9", custom.coef.map = list("active_score" = "Active learning"))
```

\newpage

## Table 6: Heterogeneity

### By gender

```{r, results='asis'}

lm1a <-
  df %>%
  filter(country == "China", female == 1) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm1b <-
  df %>%
  filter(country == "China", female == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")


lm2a <-
  df %>%
  filter(country == "India", female == 1) %>%
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm2b <-
  df %>%
  filter(country == "India", female == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm3a <-
  df %>%
  filter(country == "Russia", female == 1) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm3b <-
  df %>%
  filter(country == "Russia", female == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

knitreg(list(lm1a, lm1b, lm2a, lm2b, lm3a, lm3b), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = TRUE, custom.model.names = c("China Female", "China Male", "India Female", "India Male","Russia Female", "Russia Male"), dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 3, include.rsquared = F, include.nclust = F, include.adjrs = F, include.rmse = F, custom.coef.names = c("Active learning", "Baseline achievement", "Faculty experience", "Faculty undergrad from elite college", "Faculty graduate from elite college", "Faculty total publications", "Faculty female", "Faculty highest degree is PhD", "Professor", "Associate Professor"), label = "tab10", custom.coef.map = list("active_score" = "Active learning"))
```

\newpage

### By socioeconomic status

```{r, results='asis'}

lm1a <-
  df %>%
  filter(country == "China", ses_lowest_tercile == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm1b <-
  df %>%
  filter(country == "China", ses_lowest_tercile == 1) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm2a <-
  df %>%
  filter(country == "India", ses_lowest_tercile == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm2b <-
  df %>%
  filter(country == "India", ses_lowest_tercile == 1) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")


lm3a <-
  df %>%
  filter(country == "Russia", ses_lowest_tercile == 0) %>% 
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

lm3b <-
  df %>%
  filter(country == "Russia", ses_lowest_tercile == 1) %>%
  lm_robust(g3_score ~ active_score + g1_score + bfac_yearsinhighed + bfac_degree_college_elite + bfac_degree_univ_elite + bfac_publications + bfac_female + bfac_highest_degree_phd + bfac_professor + bfac_associate_professor, fixed_effects = ~ studentid, data = ., clusters = departmentid, se_type = "stata")

knitreg(list(lm1a, lm1b, lm2a, lm2b, lm3a, lm3b), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = TRUE, custom.model.names = c("China High SES", "China Low SES", "India High SES", "India Low SES", "Russia High SES", "Russia Low SES"), dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 3, include.rsquared = F, include.adjrs = F, include.nclust = F, include.rmse = F, custom.coef.names = c("Active learning", "Baseline achievement", "Faculty experience", "Faculty undergrad from elite college", "Faculty graduate from elite college", "Faculty total publications", "Faculty female", "Faculty highest degree is PhD", "Professor", "Associate Professor"), label = "tab11", custom.coef.map = list("active_score" = "Active learning"))
```

\newpage

## Table E4: Summary statistics

```{r, results='asis'}
df %>% 
  distinct(studentid, .keep_all = T) %>%
  compareGroups(country ~ female + age_years + father_college + mother_college, data = ., include.label = F) %>%   
  createTable(show.all = F, show.n = F, show.p.overall = F)
```
